name: Generate release

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  generate:
    name: Generate pip archive
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install package dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: make
        version: 1.0

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Build joyeuse-x.x.x.tar.gz
      run: make pip

    - name: Archive artifact
      uses: actions/upload-artifact@v3
      with:
        name: joyeuse
        path: dist/joyeuse*.tar.gz

