name: Generate release

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  generate-pip:
    name: Generate pip archive
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install package dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: make
        version: 1.0

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Build joyeuse-x.x.x.tar.gz
      run: make pip

    - name: Archive artifact
      uses: actions/upload-artifact@v3
      with:
        name: joyeuse-pip
        path: dist/joyeuse*.tar.gz

    - name: Upload pip artifact
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/joyeuse*.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

  generate-deb:
    strategy:
      matrix:
        include:
            - os: ubuntu-20.04
              suffix: ubuntu-20.04
            - os: ubuntu-22.04
              suffix: ubuntu-22.04

    name: Generate debian package
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install package dependencies
      run: sudo apt install -y devscripts debhelper dh-python python3 python3-setuptools python3-tk

    - name: Build joyeuse-x.x.x.deb
      run: |
        make debian
        mv ../joyeuse*.deb .
        tar cjf joyeuse-${{ matrix.suffix }}.tar.gz ./joyeuse*.deb

    - name: Archive artifact
      uses: actions/upload-artifact@v3
      with:
        name: joyeuse-${{ matrix.suffix }}
        path: joyeuse*.deb

    - name: Upload deb artifact
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: joyeuse-${{ matrix.suffix }}.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

  generate-windows:
    name: Generate Windows executable
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gtk4
          mingw-w64-x86_64-python3
          mingw-w64-x86_64-python3-gobject
          mingw-w64-x86_64-python3-pip
          mingw-w64-x86_64-python3-pillow
          mingw-w64-x86_64-gst-python
          mingw-w64-x86_64-gst-plugins-ugly
          mingw-w64-x86_64-gst-plugins-bad
          mingw-w64-x86_64-gst-plugins-good
          mingw-w64-x86_64-gst-plugins-base
          mingw-w64-x86_64-gstreamer
          pkg-config
    - name: Install dependencies
      run: |
        python -m pip install . pyinstaller
    - name: Build joyeuse.exe
      run: |
        pyinstaller --noconsole --paths . --onefile --name joyeuse --exclude-module _bootlocale --hidden-import=tkinter --collect-submodules=pillow "${PWD}/script/joyeuse.py"
    - name: Archive artifact
      uses: actions/upload-artifact@v3
      with:
        name: joyeuse
        path: dist/joyeuse.exe

    - name: Upload exe artifact
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/joyeuse*.exe
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

