name: Generate Windows Executable

on:
  workflow_dispatch:
  push:
    branches: [ "test-windows" ]

jobs:
  generate:
    name: Generate Windows executable
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . -r requirements.txt
    - name: Build joyeuse.exe
      run: bash .github/scripts/build-win.sh
    - name: Archive artifact
      uses: actions/upload-artifact@v3
      with:
        name: joyeuse
        path: dist/joyeuse.exe
